spring:
  application:
    name: maple-api-router-service
  cloud:
    gateway:
      httpclient:
        connect-timeout: 500
        response-timeout: 5s
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: authModule
          uri: http://maple-user-auth-service.maple-system.svc.cluster.local:8081/
          predicates:
            - Path=/api/auth/login
          filters:
            - RewritePath=/api/auth/login,/api/v1/auth/login
        - id: userAccountModule
          uri: http://maple-user-account-service.maple-system.svc.cluster.local:8081/
          predicates:
            - Path=/api/organizations/*/user-accounts/**
          filters:
            - RewritePath=/api/organizations(?<segment>.*),/api/v1/organizations$\{segment}
            - SessionResolverFilter
        - id: userAccountImageModule
          uri: http://maple-user-account-service.maple-system.svc.cluster.local:8081/
          predicates:
            - Path=/api/user-accounts/*/images/**
          filters:
            - RewritePath=/api/user-accounts(?<segment>.*),/api/v1/user-accounts$\{segment}
            - SessionResolverFilter
        - id: projectModule
          uri: http://maple-project-service.maple-system.svc.cluster.local:8081/
          predicates:
            - Path=/api/organizations/*/projects/**
          filters:
            - RewritePath=/api/organizations(?<segment>.*),/api/v1/organizations$\{segment}
            - SessionResolverFilter
        - id: organizationModule
          uri: http://maple-organization-service.maple-system.svc.cluster.local:8081/
          predicates:
            - Path=/api/organizations/**
          filters:
            - RewritePath=/api/organizations(?<segment>.*),/api/v1/organizations$\{segment}
            - SessionResolverFilter

  jackson:
    property-naming-strategy: SNAKE_CASE

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://maple-zipkin-service.maple-tracing.svc.cluster.local:9411/api/v2/spans
  prometheus:
    metrics:
      export:
        enabled: true

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 860
  error:
    include-stacktrace: never
