apiVersion: v1
kind: Service
metadata:
  name: maple-api-router-service
  namespace: maple-system
  labels:
    app: maple-api-router
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: maple-api-router