apiVersion: v1
kind: Service
metadata:
  name: maple-api-router-service
  namespace: maple-system
  labels:
    app: maple-api-router
spec:
  type: LoadBalancer
  ports:
    - name: admin
      port: 9901
      targetPort: 9901
    - name: envoy
      port: 8081
      targetPort: 8081
  selector:
    app: maple-api-router